[package]
edition = "2021"
name = "with_fetch"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.24"
reqwest = { version = "0.11", features = ["json"] }
